name: Execute workflow call manual

on:
  workflow_dispatch:
    

jobs:
  execute_workflow_call_1:
    name: Workflow call 1
    uses: ./.github/workflows/template_1.yml
    with:
      ENV_NAME: workflow_call_1
      ANOTHER_VAR: "this is sparta"
  execute_workflow_call_2:
    name: Workflow call 2
    needs: [execute_workflow_call_1]
    uses: ./.github/workflows/template_2.yml
    with:
      ENV_NAME: prod
      ANOTHER_VAR: "this is not sparta"
