name: Execute workflow call 1

on:
  push:
    branches: 
      - "qa-*"

jobs:
  execute_workflow_call_1:
    name: Workflow call 1
    uses: ./.github/workflows/template_1.yml
    with:
      ENV_NAME: workflow_call_1
      ANOTHER_VAR: "this is sparta"
  execute_workflow_call_2:
    name: Workflow call 2
    needs: [execute_workflow_call_1]
    uses: ./.github/workflows/template_2.yml
    with:
      ENV_NAME: qa
      ANOTHER_VAR: "this is not sparta"
