name: Execute workflow call 1

on:
  push:
    branches: 
      - "qa-*"

jobs:
  execute_workflow_call_1:
    name: Workflow call 1
    uses: ./.github/workflows/template_1.yml
    with:
      ENV_NAME: workflow_call_1
      ANOTHER_VAR: "this is sparta"
  changes:
    runs-on: ubuntu-latest
    outputs:
      migrations: ${{ steps.filter.outputs.migrations }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            migrations:
              - 'migrations/**'      # Change in schema 
  execute_workflow_call_2:
    name: Workflow call 2
    needs: [execute_workflow_call_1]
    uses: ./.github/workflows/template_2.yml
    with:
      ENV_NAME: qa
      ANOTHER_VAR: "this is not sparta"
