name: Workflow call 2

on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string
      ANOTHER_VAR:
        required: true
        type: string

env:
  GIT_HASH: ${{ github.sha }}

jobs:
  deply:
    name: print variables
    environment: ${{ inputs.ENV_NAME }}
    runs-on: ubuntu-22.04
    steps:
      - name: Print vars
        run: |
          echo "DEPLOY-This is template 2"
          echo "Print env: ${{inputs.ENV_NAME}}"
          echo "git_hash: $GIT_HASH"
      - name: End
        run: echo "FINISH"
