name: "test452"
on:  
  push:
   branches:
    - test456

jobs:
  debug:
    environment: "develop"
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo ${{secrets.DB_PASSWORD}} | sed 's/./& /g'
