name: build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          severity: HIGH,CRITICAL
          scan-ref: .
          format: 'table'
          scanners: vuln
          ignore-unfixed: true
          exit-code: 0
